<?php

namespace Database\Seeders;

use App\Models\ArtikelPendidikanKesehatan;
use Illuminate\Database\Seeder;

class ArtikelPendidikanKesehatanSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $artikelData = [
            [
                'judul' => '6 Aktivitas Seru untuk Balita yang Bikin Badan Tetap Fit!',
                'kategori' => 'olahraga',
                'status' => 'umum',
                'kelompok_usia' => 'semua usia',
                'nama_penerbit' => 'Farhan Ginanjar, Spg.',
                'foto_penerbit' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTSrd4DuhpuJcCoDLLineKllQGPqvyff3Okr0QaRlgOKQ&s',
                'foto_konten' => 'https://naikpangkat.com/wp-content/uploads/2022/10/pexels-lukas-296301-scaled-800x530.jpg',
                'isi_konten' => '<p>Keseruan Aktivitas Fisik: Balita Membutuhkan Gerakan untuk Tetap Enerjik! Minimal 180 Menit atau Lebih untuk Kesehatan Mereka! Lebih banyak aktivitas fisik justru lebih baik. Aktivitas ini bisa berupa gerakan ringan seperti berdiri, bergerak, berguling, dan bermain, hingga aktivitas yang lebih energik seperti melompat dan berlari.&nbsp;</p><h4><strong>Jenis Olahraga Ringan untuk Balita</strong>&nbsp;</h4><p>Berikut beberapa rekomendasi olahraga ringan yang baik untuk balita:&nbsp;</p><ul><li><p>Bermain dengan Balok&nbsp;</p><p>Menyusun dan memindahkan balok dapat melatih motorik anak. Aktivitas ini membantu keseimbangan dan koordinasi anak.&nbsp;</p></li><li><p>Bermain Lompat&nbsp;</p><p>Melompat mengikuti imajinasi atau musik adalah aktivitas yang menyenangkan bagi balita. Pastikan lingkungan sekitar aman untuk menghindari cedera.&nbsp;</p></li><li><p>Berjalan&nbsp;</p><p>Ajak balita berjalan pagi atau sore bersama. Usahakan balita menyelesaikan jalan tanpa digendong agar mereka terbiasa bergerak.&nbsp;</p></li><li><p>Menari&nbsp;</p><p>Ikuti video lagu anak yang memiliki koreografi seperti "Baby Shark". Menari bisa menjadi bagian dari olahraga ringan yang menyenangkan.&nbsp;</p></li><li><p>Renang&nbsp;</p><p>Mengajari anak renang sejak dini bisa membiasakan pola hidup sehat. Renang membantu anak tumbuh percaya diri, belajar menghadapi ketakutan, dan menjaga kebugaran tubuh.&nbsp;</p></li><li><p>Trekking&nbsp;</p><p>Ajak anak trekking dengan memilih jalur yang aman dan tidak terlalu jauh. Trekking membantu anak belajar mencintai alam dan mengurangi ketergantungan pada gadget.&nbsp;</p></li></ul><h4><strong>Manfaat Olahraga Ringan untuk Balita</strong>&nbsp;</h4><p>Menggerakkan tubuh itu baik untuk semua orang di segala usia, termasuk balita. Terutama untuk anak yang suka tantrum, olahraga memberikan manfaat seperti:&nbsp;</p><ul><li><p>Tidur Lebih Nyenyak&nbsp;</p><p>Aktivitas fisik membantu anak tertidur lebih cepat dan nyenyak, yang baik untuk kesehatan dan pertumbuhan otaknya.&nbsp;</p></li><li><p>Mood yang Lebih Baik&nbsp;</p><p>Aktivitas fisik merangsang senyawa kimia otak, membantu anak menghilangkan stres dan meningkatkan fokus.&nbsp;</p></li><li><p>Meningkatkan Sistem Imun Tubuh&nbsp;</p><p>Olahraga dapat meningkatkan kekebalan tubuh anak, menurunkan risiko penyakit seperti jantung, diabetes, atau tekanan darah tinggi.&nbsp;</p></li><li><p>Memperkuat Tulang, Paru-paru, Otot, dan Jantung&nbsp;</p><p>Olahraga memperkuat sistem tubuh anak secara keseluruhan.&nbsp;</p></li></ul><h4><strong>Kesimpulan</strong>&nbsp;</h4><p>Olahraga ringan penting untuk perkembangan dan kesehatan balita. Pastikan mereka aktif setiap hari dengan cara yang menyenangkan dan aman.&nbsp;</p>',
                'tanggal' => '2024-04-20',
            ],
            [
                'judul' => 'Balita Terlalu Kurus, Awas Malabsorpsi Kronis',
                'kategori' => 'pertumbuhan anak',
                'status' => 'underweight',
                'kelompok_usia' => 'bayi',
                'nama_penerbit' => 'Ghina Aulia',
                'foto_penerbit' => 'https://htmlcolorcodes.com/assets/images/colors/light-green-color-solid-background-1920x1080.png',
                'foto_konten' => 'https://www.parents.com/thmb/ESyv0-nu1ZIFlOoZkdDggoaElTU=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/GettyImages-821529326-d760ce7d812a46d0bf29a56589868cc9.jpg',
                'isi_konten' => '<p>Keseruan Aktivitas Fisik: Balita Membutuhkan Gerakan untuk Tetap Enerjik! Minimal 180 Menit atau Lebih untuk Kesehatan Mereka! Lebih banyak aktivitas fisik justru lebih baik. Aktivitas ini bisa berupa gerakan ringan seperti berdiri, bergerak, berguling, dan bermain, hingga aktivitas yang lebih energik seperti melompat dan berlari.&nbsp;</p><h4><strong>Jenis Olahraga Ringan untuk Balita</strong>&nbsp;</h4><p>Berikut beberapa rekomendasi olahraga ringan yang baik untuk balita:&nbsp;</p><ul><li><p>Bermain dengan Balok&nbsp;</p><p>Menyusun dan memindahkan balok dapat melatih motorik anak. Aktivitas ini membantu keseimbangan dan koordinasi anak.&nbsp;</p></li><li><p>Bermain Lompat&nbsp;</p><p>Melompat mengikuti imajinasi atau musik adalah aktivitas yang menyenangkan bagi balita. Pastikan lingkungan sekitar aman untuk menghindari cedera.&nbsp;</p></li><li><p>Berjalan&nbsp;</p><p>Ajak balita berjalan pagi atau sore bersama. Usahakan balita menyelesaikan jalan tanpa digendong agar mereka terbiasa bergerak.&nbsp;</p></li><li><p>Menari&nbsp;</p><p>Ikuti video lagu anak yang memiliki koreografi seperti "Baby Shark". Menari bisa menjadi bagian dari olahraga ringan yang menyenangkan.&nbsp;</p></li><li><p>Renang&nbsp;</p><p>Mengajari anak renang sejak dini bisa membiasakan pola hidup sehat. Renang membantu anak tumbuh percaya diri, belajar menghadapi ketakutan, dan menjaga kebugaran tubuh.&nbsp;</p></li><li><p>Trekking&nbsp;</p><p>Ajak anak trekking dengan memilih jalur yang aman dan tidak terlalu jauh. Trekking membantu anak belajar mencintai alam dan mengurangi ketergantungan pada gadget.&nbsp;</p></li></ul><h4><strong>Manfaat Olahraga Ringan untuk Balita</strong>&nbsp;</h4><p>Menggerakkan tubuh itu baik untuk semua orang di segala usia, termasuk balita. Terutama untuk anak yang suka tantrum, olahraga memberikan manfaat seperti:&nbsp;</p><ul><li><p>Tidur Lebih Nyenyak&nbsp;</p><p>Aktivitas fisik membantu anak tertidur lebih cepat dan nyenyak, yang baik untuk kesehatan dan pertumbuhan otaknya.&nbsp;</p></li><li><p>Mood yang Lebih Baik&nbsp;</p><p>Aktivitas fisik merangsang senyawa kimia otak, membantu anak menghilangkan stres dan meningkatkan fokus.&nbsp;</p></li><li><p>Meningkatkan Sistem Imun Tubuh&nbsp;</p><p>Olahraga dapat meningkatkan kekebalan tubuh anak, menurunkan risiko penyakit seperti jantung, diabetes, atau tekanan darah tinggi.&nbsp;</p></li><li><p>Memperkuat Tulang, Paru-paru, Otot, dan Jantung&nbsp;</p><p>Olahraga memperkuat sistem tubuh anak secara keseluruhan.&nbsp;</p></li></ul><h4><strong>Kesimpulan</strong>&nbsp;</h4><p>Olahraga ringan penting untuk perkembangan dan kesehatan balita. Pastikan mereka aktif setiap hari dengan cara yang menyenangkan dan aman.&nbsp;</p>',
                'tanggal' => '2024-06-26',
            ],
            [
                'judul' => 'Cara Tepat Bagi Ibu untuk Mencegah Stunting',
                'kategori' => 'pertumbuhan anak',
                'status' => 'stunting',
                'kelompok_usia' => 'anak',
                'nama_penerbit' => 'UNICEF',
                'foto_penerbit' => 'https://www.geaves.com/media/catalog/product/cache/acd115faf6a75f6594ab269049b631ed/3/1/31552_5.webp',
                'foto_konten' => 'https://cdn1-production-images-kly.akamaized.net/M5nAT62pzQ24BbzghU3zS9AGE7I=/1280x720/smart/filters:quality(75):strip_icc():format(webp)/kly-media-production/medias/1399264/original/035742100_1478604210-bellamysorganic_com_au.jpg',
                'isi_konten' => '<p>Keseruan Aktivitas Fisik: Balita Membutuhkan Gerakan untuk Tetap Enerjik! Minimal 180 Menit atau Lebih untuk Kesehatan Mereka! Lebih banyak aktivitas fisik justru lebih baik. Aktivitas ini bisa berupa gerakan ringan seperti berdiri, bergerak, berguling, dan bermain, hingga aktivitas yang lebih energik seperti melompat dan berlari.&nbsp;</p><h4><strong>Jenis Olahraga Ringan untuk Balita</strong>&nbsp;</h4><p>Berikut beberapa rekomendasi olahraga ringan yang baik untuk balita:&nbsp;</p><ul><li><p>Bermain dengan Balok&nbsp;</p><p>Menyusun dan memindahkan balok dapat melatih motorik anak. Aktivitas ini membantu keseimbangan dan koordinasi anak.&nbsp;</p></li><li><p>Bermain Lompat&nbsp;</p><p>Melompat mengikuti imajinasi atau musik adalah aktivitas yang menyenangkan bagi balita. Pastikan lingkungan sekitar aman untuk menghindari cedera.&nbsp;</p></li><li><p>Berjalan&nbsp;</p><p>Ajak balita berjalan pagi atau sore bersama. Usahakan balita menyelesaikan jalan tanpa digendong agar mereka terbiasa bergerak.&nbsp;</p></li><li><p>Menari&nbsp;</p><p>Ikuti video lagu anak yang memiliki koreografi seperti "Baby Shark". Menari bisa menjadi bagian dari olahraga ringan yang menyenangkan.&nbsp;</p></li><li><p>Renang&nbsp;</p><p>Mengajari anak renang sejak dini bisa membiasakan pola hidup sehat. Renang membantu anak tumbuh percaya diri, belajar menghadapi ketakutan, dan menjaga kebugaran tubuh.&nbsp;</p></li><li><p>Trekking&nbsp;</p><p>Ajak anak trekking dengan memilih jalur yang aman dan tidak terlalu jauh. Trekking membantu anak belajar mencintai alam dan mengurangi ketergantungan pada gadget.&nbsp;</p></li></ul><h4><strong>Manfaat Olahraga Ringan untuk Balita</strong>&nbsp;</h4><p>Menggerakkan tubuh itu baik untuk semua orang di segala usia, termasuk balita. Terutama untuk anak yang suka tantrum, olahraga memberikan manfaat seperti:&nbsp;</p><ul><li><p>Tidur Lebih Nyenyak&nbsp;</p><p>Aktivitas fisik membantu anak tertidur lebih cepat dan nyenyak, yang baik untuk kesehatan dan pertumbuhan otaknya.&nbsp;</p></li><li><p>Mood yang Lebih Baik&nbsp;</p><p>Aktivitas fisik merangsang senyawa kimia otak, membantu anak menghilangkan stres dan meningkatkan fokus.&nbsp;</p></li><li><p>Meningkatkan Sistem Imun Tubuh&nbsp;</p><p>Olahraga dapat meningkatkan kekebalan tubuh anak, menurunkan risiko penyakit seperti jantung, diabetes, atau tekanan darah tinggi.&nbsp;</p></li><li><p>Memperkuat Tulang, Paru-paru, Otot, dan Jantung&nbsp;</p><p>Olahraga memperkuat sistem tubuh anak secara keseluruhan.&nbsp;</p></li></ul><h4><strong>Kesimpulan</strong>&nbsp;</h4><p>Olahraga ringan penting untuk perkembangan dan kesehatan balita. Pastikan mereka aktif setiap hari dengan cara yang menyenangkan dan aman.&nbsp;</p>',
                'tanggal' => '2024-06-24',
            ],
            [
                'judul' => 'Singkong Membantu Mengurangi Risiko Stunting',
                'kategori' => 'pertumbuhan anak',
                'status' => 'stunting',
                'kelompok_usia' => 'batita',
                'nama_penerbit' => 'Sinta Harumi',
                'foto_penerbit' => 'https://t4.ftcdn.net/jpg/05/06/41/89/360_F_506418953_5R5MQsN4UJ4hLgqnKlltS44wbQ33LhIU.jpg',
                'foto_konten' => 'https://media.suara.com/pictures/653x366/2021/11/12/37918-ilustrasi-makanan-dari-singkong-pixabaykavindaf.webp',
                'isi_konten' => '<p>Keseruan Aktivitas Fisik: Balita Membutuhkan Gerakan untuk Tetap Enerjik! Minimal 180 Menit atau Lebih untuk Kesehatan Mereka! Lebih banyak aktivitas fisik justru lebih baik. Aktivitas ini bisa berupa gerakan ringan seperti berdiri, bergerak, berguling, dan bermain, hingga aktivitas yang lebih energik seperti melompat dan berlari.&nbsp;</p><h4><strong>Jenis Olahraga Ringan untuk Balita</strong>&nbsp;</h4><p>Berikut beberapa rekomendasi olahraga ringan yang baik untuk balita:&nbsp;</p><ul><li><p>Bermain dengan Balok&nbsp;</p><p>Menyusun dan memindahkan balok dapat melatih motorik anak. Aktivitas ini membantu keseimbangan dan koordinasi anak.&nbsp;</p></li><li><p>Bermain Lompat&nbsp;</p><p>Melompat mengikuti imajinasi atau musik adalah aktivitas yang menyenangkan bagi balita. Pastikan lingkungan sekitar aman untuk menghindari cedera.&nbsp;</p></li><li><p>Berjalan&nbsp;</p><p>Ajak balita berjalan pagi atau sore bersama. Usahakan balita menyelesaikan jalan tanpa digendong agar mereka terbiasa bergerak.&nbsp;</p></li><li><p>Menari&nbsp;</p><p>Ikuti video lagu anak yang memiliki koreografi seperti "Baby Shark". Menari bisa menjadi bagian dari olahraga ringan yang menyenangkan.&nbsp;</p></li><li><p>Renang&nbsp;</p><p>Mengajari anak renang sejak dini bisa membiasakan pola hidup sehat. Renang membantu anak tumbuh percaya diri, belajar menghadapi ketakutan, dan menjaga kebugaran tubuh.&nbsp;</p></li><li><p>Trekking&nbsp;</p><p>Ajak anak trekking dengan memilih jalur yang aman dan tidak terlalu jauh. Trekking membantu anak belajar mencintai alam dan mengurangi ketergantungan pada gadget.&nbsp;</p></li></ul><h4><strong>Manfaat Olahraga Ringan untuk Balita</strong>&nbsp;</h4><p>Menggerakkan tubuh itu baik untuk semua orang di segala usia, termasuk balita. Terutama untuk anak yang suka tantrum, olahraga memberikan manfaat seperti:&nbsp;</p><ul><li><p>Tidur Lebih Nyenyak&nbsp;</p><p>Aktivitas fisik membantu anak tertidur lebih cepat dan nyenyak, yang baik untuk kesehatan dan pertumbuhan otaknya.&nbsp;</p></li><li><p>Mood yang Lebih Baik&nbsp;</p><p>Aktivitas fisik merangsang senyawa kimia otak, membantu anak menghilangkan stres dan meningkatkan fokus.&nbsp;</p></li><li><p>Meningkatkan Sistem Imun Tubuh&nbsp;</p><p>Olahraga dapat meningkatkan kekebalan tubuh anak, menurunkan risiko penyakit seperti jantung, diabetes, atau tekanan darah tinggi.&nbsp;</p></li><li><p>Memperkuat Tulang, Paru-paru, Otot, dan Jantung&nbsp;</p><p>Olahraga memperkuat sistem tubuh anak secara keseluruhan.&nbsp;</p></li></ul><h4><strong>Kesimpulan</strong>&nbsp;</h4><p>Olahraga ringan penting untuk perkembangan dan kesehatan balita. Pastikan mereka aktif setiap hari dengan cara yang menyenangkan dan aman.&nbsp;</p>',
                'tanggal' => '2024-01-01',
            ],
            [
                'judul' => 'Mengatasi Berat Badan Kurang pada Anak',
                'kategori' => 'panduan orang tua',
                'status' => 'underweight',
                'kelompok_usia' => 'hamil',
                'nama_penerbit' => 'Sinta Harumi',
                'foto_penerbit' => 'https://t4.ftcdn.net/jpg/05/06/41/89/360_F_506418953_5R5MQsN4UJ4hLgqnKlltS44wbQ33LhIU.jpg',
                'foto_konten' => 'https://www.ibudanbalita.com/uploads/posts/uKj7QaV2jc.jpg',
                'isi_konten' => '<p>Keseruan Aktivitas Fisik: Balita Membutuhkan Gerakan untuk Tetap Enerjik! Minimal 180 Menit atau Lebih untuk Kesehatan Mereka! Lebih banyak aktivitas fisik justru lebih baik. Aktivitas ini bisa berupa gerakan ringan seperti berdiri, bergerak, berguling, dan bermain, hingga aktivitas yang lebih energik seperti melompat dan berlari.&nbsp;</p><h4><strong>Jenis Olahraga Ringan untuk Balita</strong>&nbsp;</h4><p>Berikut beberapa rekomendasi olahraga ringan yang baik untuk balita:&nbsp;</p><ul><li><p>Bermain dengan Balok&nbsp;</p><p>Menyusun dan memindahkan balok dapat melatih motorik anak. Aktivitas ini membantu keseimbangan dan koordinasi anak.&nbsp;</p></li><li><p>Bermain Lompat&nbsp;</p><p>Melompat mengikuti imajinasi atau musik adalah aktivitas yang menyenangkan bagi balita. Pastikan lingkungan sekitar aman untuk menghindari cedera.&nbsp;</p></li><li><p>Berjalan&nbsp;</p><p>Ajak balita berjalan pagi atau sore bersama. Usahakan balita menyelesaikan jalan tanpa digendong agar mereka terbiasa bergerak.&nbsp;</p></li><li><p>Menari&nbsp;</p><p>Ikuti video lagu anak yang memiliki koreografi seperti "Baby Shark". Menari bisa menjadi bagian dari olahraga ringan yang menyenangkan.&nbsp;</p></li><li><p>Renang&nbsp;</p><p>Mengajari anak renang sejak dini bisa membiasakan pola hidup sehat. Renang membantu anak tumbuh percaya diri, belajar menghadapi ketakutan, dan menjaga kebugaran tubuh.&nbsp;</p></li><li><p>Trekking&nbsp;</p><p>Ajak anak trekking dengan memilih jalur yang aman dan tidak terlalu jauh. Trekking membantu anak belajar mencintai alam dan mengurangi ketergantungan pada gadget.&nbsp;</p></li></ul><h4><strong>Manfaat Olahraga Ringan untuk Balita</strong>&nbsp;</h4><p>Menggerakkan tubuh itu baik untuk semua orang di segala usia, termasuk balita. Terutama untuk anak yang suka tantrum, olahraga memberikan manfaat seperti:&nbsp;</p><ul><li><p>Tidur Lebih Nyenyak&nbsp;</p><p>Aktivitas fisik membantu anak tertidur lebih cepat dan nyenyak, yang baik untuk kesehatan dan pertumbuhan otaknya.&nbsp;</p></li><li><p>Mood yang Lebih Baik&nbsp;</p><p>Aktivitas fisik merangsang senyawa kimia otak, membantu anak menghilangkan stres dan meningkatkan fokus.&nbsp;</p></li><li><p>Meningkatkan Sistem Imun Tubuh&nbsp;</p><p>Olahraga dapat meningkatkan kekebalan tubuh anak, menurunkan risiko penyakit seperti jantung, diabetes, atau tekanan darah tinggi.&nbsp;</p></li><li><p>Memperkuat Tulang, Paru-paru, Otot, dan Jantung&nbsp;</p><p>Olahraga memperkuat sistem tubuh anak secara keseluruhan.&nbsp;</p></li></ul><h4><strong>Kesimpulan</strong>&nbsp;</h4><p>Olahraga ringan penting untuk perkembangan dan kesehatan balita. Pastikan mereka aktif setiap hari dengan cara yang menyenangkan dan aman.&nbsp;</p>',
                'tanggal' => '2024-01-01',
            ],
            [
                'judul' => 'Penyebab dan Dampak Underweight',
                'kategori' => 'panduan orang tua',
                'status' => 'underweight',
                'kelompok_usia' => 'hamil',
                'nama_penerbit' => 'Hana Amani',
                'foto_penerbit' => 'https://t4.ftcdn.net/jpg/05/06/41/89/360_F_506418953_5R5MQsN4UJ4hLgqnKlltS44wbQ33LhIU.jpg',
                'foto_konten' => 'https://images.onlymyhealth.com/imported/images/2023/April/19_Apr_2023/Main.jpg',
                'isi_konten' => '<p>Keseruan Aktivitas Fisik: Balita Membutuhkan Gerakan untuk Tetap Enerjik! Minimal 180 Menit atau Lebih untuk Kesehatan Mereka! Lebih banyak aktivitas fisik justru lebih baik. Aktivitas ini bisa berupa gerakan ringan seperti berdiri, bergerak, berguling, dan bermain, hingga aktivitas yang lebih energik seperti melompat dan berlari.&nbsp;</p><h4><strong>Jenis Olahraga Ringan untuk Balita</strong>&nbsp;</h4><p>Berikut beberapa rekomendasi olahraga ringan yang baik untuk balita:&nbsp;</p><ul><li><p>Bermain dengan Balok&nbsp;</p><p>Menyusun dan memindahkan balok dapat melatih motorik anak. Aktivitas ini membantu keseimbangan dan koordinasi anak.&nbsp;</p></li><li><p>Bermain Lompat&nbsp;</p><p>Melompat mengikuti imajinasi atau musik adalah aktivitas yang menyenangkan bagi balita. Pastikan lingkungan sekitar aman untuk menghindari cedera.&nbsp;</p></li><li><p>Berjalan&nbsp;</p><p>Ajak balita berjalan pagi atau sore bersama. Usahakan balita menyelesaikan jalan tanpa digendong agar mereka terbiasa bergerak.&nbsp;</p></li><li><p>Menari&nbsp;</p><p>Ikuti video lagu anak yang memiliki koreografi seperti "Baby Shark". Menari bisa menjadi bagian dari olahraga ringan yang menyenangkan.&nbsp;</p></li><li><p>Renang&nbsp;</p><p>Mengajari anak renang sejak dini bisa membiasakan pola hidup sehat. Renang membantu anak tumbuh percaya diri, belajar menghadapi ketakutan, dan menjaga kebugaran tubuh.&nbsp;</p></li><li><p>Trekking&nbsp;</p><p>Ajak anak trekking dengan memilih jalur yang aman dan tidak terlalu jauh. Trekking membantu anak belajar mencintai alam dan mengurangi ketergantungan pada gadget.&nbsp;</p></li></ul><h4><strong>Manfaat Olahraga Ringan untuk Balita</strong>&nbsp;</h4><p>Menggerakkan tubuh itu baik untuk semua orang di segala usia, termasuk balita. Terutama untuk anak yang suka tantrum, olahraga memberikan manfaat seperti:&nbsp;</p><ul><li><p>Tidur Lebih Nyenyak&nbsp;</p><p>Aktivitas fisik membantu anak tertidur lebih cepat dan nyenyak, yang baik untuk kesehatan dan pertumbuhan otaknya.&nbsp;</p></li><li><p>Mood yang Lebih Baik&nbsp;</p><p>Aktivitas fisik merangsang senyawa kimia otak, membantu anak menghilangkan stres dan meningkatkan fokus.&nbsp;</p></li><li><p>Meningkatkan Sistem Imun Tubuh&nbsp;</p><p>Olahraga dapat meningkatkan kekebalan tubuh anak, menurunkan risiko penyakit seperti jantung, diabetes, atau tekanan darah tinggi.&nbsp;</p></li><li><p>Memperkuat Tulang, Paru-paru, Otot, dan Jantung&nbsp;</p><p>Olahraga memperkuat sistem tubuh anak secara keseluruhan.&nbsp;</p></li></ul><h4><strong>Kesimpulan</strong>&nbsp;</h4><p>Olahraga ringan penting untuk perkembangan dan kesehatan balita. Pastikan mereka aktif setiap hari dengan cara yang menyenangkan dan aman.&nbsp;</p>',
                'tanggal' => '2024-01-01',
            ],
            [
                'judul' => 'Manfaat dan Risiko MPASI Dini pada Bayi',
                'kategori' => 'panduan orang tua',
                'status' => 'underweight',
                'kelompok_usia' => 'hamil',
                'nama_penerbit' => 'Dea Nur Rahmat',
                'foto_penerbit' => 'https://t4.ftcdn.net/jpg/05/06/41/89/360_F_506418953_5R5MQsN4UJ4hLgqnKlltS44wbQ33LhIU.jpg',
                'foto_konten' => 'https://d1bpj0tv6vfxyp.cloudfront.net/articles/786062_6-10-2020_19-30-58.jpeg',
                'isi_konten' => '<p>Keseruan Aktivitas Fisik: Balita Membutuhkan Gerakan untuk Tetap Enerjik! Minimal 180 Menit atau Lebih untuk Kesehatan Mereka! Lebih banyak aktivitas fisik justru lebih baik. Aktivitas ini bisa berupa gerakan ringan seperti berdiri, bergerak, berguling, dan bermain, hingga aktivitas yang lebih energik seperti melompat dan berlari.&nbsp;</p><h4><strong>Jenis Olahraga Ringan untuk Balita</strong>&nbsp;</h4><p>Berikut beberapa rekomendasi olahraga ringan yang baik untuk balita:&nbsp;</p><ul><li><p>Bermain dengan Balok&nbsp;</p><p>Menyusun dan memindahkan balok dapat melatih motorik anak. Aktivitas ini membantu keseimbangan dan koordinasi anak.&nbsp;</p></li><li><p>Bermain Lompat&nbsp;</p><p>Melompat mengikuti imajinasi atau musik adalah aktivitas yang menyenangkan bagi balita. Pastikan lingkungan sekitar aman untuk menghindari cedera.&nbsp;</p></li><li><p>Berjalan&nbsp;</p><p>Ajak balita berjalan pagi atau sore bersama. Usahakan balita menyelesaikan jalan tanpa digendong agar mereka terbiasa bergerak.&nbsp;</p></li><li><p>Menari&nbsp;</p><p>Ikuti video lagu anak yang memiliki koreografi seperti "Baby Shark". Menari bisa menjadi bagian dari olahraga ringan yang menyenangkan.&nbsp;</p></li><li><p>Renang&nbsp;</p><p>Mengajari anak renang sejak dini bisa membiasakan pola hidup sehat. Renang membantu anak tumbuh percaya diri, belajar menghadapi ketakutan, dan menjaga kebugaran tubuh.&nbsp;</p></li><li><p>Trekking&nbsp;</p><p>Ajak anak trekking dengan memilih jalur yang aman dan tidak terlalu jauh. Trekking membantu anak belajar mencintai alam dan mengurangi ketergantungan pada gadget.&nbsp;</p></li></ul><h4><strong>Manfaat Olahraga Ringan untuk Balita</strong>&nbsp;</h4><p>Menggerakkan tubuh itu baik untuk semua orang di segala usia, termasuk balita. Terutama untuk anak yang suka tantrum, olahraga memberikan manfaat seperti:&nbsp;</p><ul><li><p>Tidur Lebih Nyenyak&nbsp;</p><p>Aktivitas fisik membantu anak tertidur lebih cepat dan nyenyak, yang baik untuk kesehatan dan pertumbuhan otaknya.&nbsp;</p></li><li><p>Mood yang Lebih Baik&nbsp;</p><p>Aktivitas fisik merangsang senyawa kimia otak, membantu anak menghilangkan stres dan meningkatkan fokus.&nbsp;</p></li><li><p>Meningkatkan Sistem Imun Tubuh&nbsp;</p><p>Olahraga dapat meningkatkan kekebalan tubuh anak, menurunkan risiko penyakit seperti jantung, diabetes, atau tekanan darah tinggi.&nbsp;</p></li><li><p>Memperkuat Tulang, Paru-paru, Otot, dan Jantung&nbsp;</p><p>Olahraga memperkuat sistem tubuh anak secara keseluruhan.&nbsp;</p></li></ul><h4><strong>Kesimpulan</strong>&nbsp;</h4><p>Olahraga ringan penting untuk perkembangan dan kesehatan balita. Pastikan mereka aktif setiap hari dengan cara yang menyenangkan dan aman.&nbsp;</p>',
                'tanggal' => '2024-01-01',
            ],
            [
                'judul' => 'Solusi Energi Selama Kehamilan: Mencegah BBLR',
                'kategori' => 'makanan dan nutrisi anak',
                'status' => 'umum',
                'kelompok_usia' => 'semua usia',
                'nama_penerbit' => 'Fabio Siregar',
                'foto_penerbit' => 'https://t4.ftcdn.net/jpg/05/06/41/89/360_F_506418953_5R5MQsN4UJ4hLgqnKlltS44wbQ33LhIU.jpg',
                'foto_konten' => 'https://img-cdn.medkomtek.com/h-w9GW-1A6CR1jBxmBm5Oi8L3vQ=/0x0/smart/filters:quality(100):format(webp)/article/lwNunKTLkwsvioX6G-1OX/original/028771000_1583808336-Sumber-Protein-untuk-Ibu-Hamil-Guna-Mencegah-Berat-Badan-Lahir-Rendah-By-Nattaro-Ohe-shutterstock_comp.jpg',
                'isi_konten' => '<p>Keseruan Aktivitas Fisik: Balita Membutuhkan Gerakan untuk Tetap Enerjik! Minimal 180 Menit atau Lebih untuk Kesehatan Mereka! Lebih banyak aktivitas fisik justru lebih baik. Aktivitas ini bisa berupa gerakan ringan seperti berdiri, bergerak, berguling, dan bermain, hingga aktivitas yang lebih energik seperti melompat dan berlari.&nbsp;</p><h4><strong>Jenis Olahraga Ringan untuk Balita</strong>&nbsp;</h4><p>Berikut beberapa rekomendasi olahraga ringan yang baik untuk balita:&nbsp;</p><ul><li><p>Bermain dengan Balok&nbsp;</p><p>Menyusun dan memindahkan balok dapat melatih motorik anak. Aktivitas ini membantu keseimbangan dan koordinasi anak.&nbsp;</p></li><li><p>Bermain Lompat&nbsp;</p><p>Melompat mengikuti imajinasi atau musik adalah aktivitas yang menyenangkan bagi balita. Pastikan lingkungan sekitar aman untuk menghindari cedera.&nbsp;</p></li><li><p>Berjalan&nbsp;</p><p>Ajak balita berjalan pagi atau sore bersama. Usahakan balita menyelesaikan jalan tanpa digendong agar mereka terbiasa bergerak.&nbsp;</p></li><li><p>Menari&nbsp;</p><p>Ikuti video lagu anak yang memiliki koreografi seperti "Baby Shark". Menari bisa menjadi bagian dari olahraga ringan yang menyenangkan.&nbsp;</p></li><li><p>Renang&nbsp;</p><p>Mengajari anak renang sejak dini bisa membiasakan pola hidup sehat. Renang membantu anak tumbuh percaya diri, belajar menghadapi ketakutan, dan menjaga kebugaran tubuh.&nbsp;</p></li><li><p>Trekking&nbsp;</p><p>Ajak anak trekking dengan memilih jalur yang aman dan tidak terlalu jauh. Trekking membantu anak belajar mencintai alam dan mengurangi ketergantungan pada gadget.&nbsp;</p></li></ul><h4><strong>Manfaat Olahraga Ringan untuk Balita</strong>&nbsp;</h4><p>Menggerakkan tubuh itu baik untuk semua orang di segala usia, termasuk balita. Terutama untuk anak yang suka tantrum, olahraga memberikan manfaat seperti:&nbsp;</p><ul><li><p>Tidur Lebih Nyenyak&nbsp;</p><p>Aktivitas fisik membantu anak tertidur lebih cepat dan nyenyak, yang baik untuk kesehatan dan pertumbuhan otaknya.&nbsp;</p></li><li><p>Mood yang Lebih Baik&nbsp;</p><p>Aktivitas fisik merangsang senyawa kimia otak, membantu anak menghilangkan stres dan meningkatkan fokus.&nbsp;</p></li><li><p>Meningkatkan Sistem Imun Tubuh&nbsp;</p><p>Olahraga dapat meningkatkan kekebalan tubuh anak, menurunkan risiko penyakit seperti jantung, diabetes, atau tekanan darah tinggi.&nbsp;</p></li><li><p>Memperkuat Tulang, Paru-paru, Otot, dan Jantung&nbsp;</p><p>Olahraga memperkuat sistem tubuh anak secara keseluruhan.&nbsp;</p></li></ul><h4><strong>Kesimpulan</strong>&nbsp;</h4><p>Olahraga ringan penting untuk perkembangan dan kesehatan balita. Pastikan mereka aktif setiap hari dengan cara yang menyenangkan dan aman.&nbsp;</p>',
                'tanggal' => '2024-01-01',
            ],
            [
                'judul' => 'Benarkah Makanan Pedas Membahayakan Janin?',
                'kategori' => 'makanan dan nutrisi anak',
                'status' => 'umum',
                'kelompok_usia' => 'semua usia',
                'nama_penerbit' => 'Clara Asri Utami',
                'foto_penerbit' => 'https://t4.ftcdn.net/jpg/05/06/41/89/360_F_506418953_5R5MQsN4UJ4hLgqnKlltS44wbQ33LhIU.jpg',
                'foto_konten' => 'https://genbest.id/images/article/769171D4-8F1F-4D90-84AC-B3B9D91E8F6D_original_731.jpeg?1703607147',
                'isi_konten' => '<p>Keseruan Aktivitas Fisik: Balita Membutuhkan Gerakan untuk Tetap Enerjik! Minimal 180 Menit atau Lebih untuk Kesehatan Mereka! Lebih banyak aktivitas fisik justru lebih baik. Aktivitas ini bisa berupa gerakan ringan seperti berdiri, bergerak, berguling, dan bermain, hingga aktivitas yang lebih energik seperti melompat dan berlari.&nbsp;</p><h4><strong>Jenis Olahraga Ringan untuk Balita</strong>&nbsp;</h4><p>Berikut beberapa rekomendasi olahraga ringan yang baik untuk balita:&nbsp;</p><ul><li><p>Bermain dengan Balok&nbsp;</p><p>Menyusun dan memindahkan balok dapat melatih motorik anak. Aktivitas ini membantu keseimbangan dan koordinasi anak.&nbsp;</p></li><li><p>Bermain Lompat&nbsp;</p><p>Melompat mengikuti imajinasi atau musik adalah aktivitas yang menyenangkan bagi balita. Pastikan lingkungan sekitar aman untuk menghindari cedera.&nbsp;</p></li><li><p>Berjalan&nbsp;</p><p>Ajak balita berjalan pagi atau sore bersama. Usahakan balita menyelesaikan jalan tanpa digendong agar mereka terbiasa bergerak.&nbsp;</p></li><li><p>Menari&nbsp;</p><p>Ikuti video lagu anak yang memiliki koreografi seperti "Baby Shark". Menari bisa menjadi bagian dari olahraga ringan yang menyenangkan.&nbsp;</p></li><li><p>Renang&nbsp;</p><p>Mengajari anak renang sejak dini bisa membiasakan pola hidup sehat. Renang membantu anak tumbuh percaya diri, belajar menghadapi ketakutan, dan menjaga kebugaran tubuh.&nbsp;</p></li><li><p>Trekking&nbsp;</p><p>Ajak anak trekking dengan memilih jalur yang aman dan tidak terlalu jauh. Trekking membantu anak belajar mencintai alam dan mengurangi ketergantungan pada gadget.&nbsp;</p></li></ul><h4><strong>Manfaat Olahraga Ringan untuk Balita</strong>&nbsp;</h4><p>Menggerakkan tubuh itu baik untuk semua orang di segala usia, termasuk balita. Terutama untuk anak yang suka tantrum, olahraga memberikan manfaat seperti:&nbsp;</p><ul><li><p>Tidur Lebih Nyenyak&nbsp;</p><p>Aktivitas fisik membantu anak tertidur lebih cepat dan nyenyak, yang baik untuk kesehatan dan pertumbuhan otaknya.&nbsp;</p></li><li><p>Mood yang Lebih Baik&nbsp;</p><p>Aktivitas fisik merangsang senyawa kimia otak, membantu anak menghilangkan stres dan meningkatkan fokus.&nbsp;</p></li><li><p>Meningkatkan Sistem Imun Tubuh&nbsp;</p><p>Olahraga dapat meningkatkan kekebalan tubuh anak, menurunkan risiko penyakit seperti jantung, diabetes, atau tekanan darah tinggi.&nbsp;</p></li><li><p>Memperkuat Tulang, Paru-paru, Otot, dan Jantung&nbsp;</p><p>Olahraga memperkuat sistem tubuh anak secara keseluruhan.&nbsp;</p></li></ul><h4><strong>Kesimpulan</strong>&nbsp;</h4><p>Olahraga ringan penting untuk perkembangan dan kesehatan balita. Pastikan mereka aktif setiap hari dengan cara yang menyenangkan dan aman.&nbsp;</p>',
                'tanggal' => '2024-01-01',
            ],

        ];

        foreach ($artikelData as $key => $val) {
            ArtikelPendidikanKesehatan::create($val);
        }
    }
}
